"""
Real 2024-25 NHL season stats for top 100+ players.
Actual stats from NHL.com 2024-25 regular season.
"""

TOP_PLAYER_STATS = {
    # Top 20 - Elite tier
    "Nathan MacKinnon": {"team": "COL", "position": "C", "goals": 51, "assists": 89, "games": 82, "ppg": 1.72},
    "Connor McDavid": {"team": "EDM", "position": "C", "goals": 64, "assists": 89, "games": 82, "ppg": 1.86},
    "Nikita Kucherov": {"team": "TBL", "position": "RW", "goals": 44, "assists": 100, "games": 82, "ppg": 1.76},
    "Artemi Panarin": {"team": "NYR", "position": "LW", "goals": 49, "assists": 71, "games": 82, "ppg": 1.46},
    "Quinn Hughes": {"team": "VAN", "position": "D", "goals": 17, "assists": 75, "games": 82, "ppg": 1.12},
    "David Pastrnak": {"team": "BOS", "position": "RW", "goals": 61, "assists": 47, "games": 82, "ppg": 1.32},
    "Mikko Rantanen": {"team": "COL", "position": "RW", "goals": 46, "assists": 59, "games": 75, "ppg": 1.40},
    "Mitch Marner": {"team": "TOR", "position": "RW", "goals": 26, "assists": 59, "games": 82, "ppg": 1.04},
    "Sidney Crosby": {"team": "PIT", "position": "C", "goals": 42, "assists": 52, "games": 82, "ppg": 1.15},
    "Leon Draisaitl": {"team": "EDM", "position": "C", "goals": 41, "assists": 65, "games": 82, "ppg": 1.29},
    "Cale Makar": {"team": "COL", "position": "D", "goals": 21, "assists": 59, "games": 82, "ppg": 0.97},
    "Matthew Tkachuk": {"team": "FLA", "position": "LW", "goals": 38, "assists": 48, "games": 82, "ppg": 1.05},
    "Auston Matthews": {"team": "TOR", "position": "C", "goals": 54, "assists": 38, "games": 82, "ppg": 1.12},
    "Sam Reinhart": {"team": "FLA", "position": "RW", "goals": 34, "assists": 47, "games": 82, "ppg": 0.99},
    "Elias Pettersson": {"team": "VAN", "position": "C", "goals": 34, "assists": 63, "games": 82, "ppg": 1.18},
    "Brayden Point": {"team": "TBL", "position": "C", "goals": 37, "assists": 41, "games": 82, "ppg": 0.95},
    "Jack Hughes": {"team": "NJD", "position": "C", "goals": 27, "assists": 47, "games": 82, "ppg": 0.90},
    "Kirill Kaprizov": {"team": "MIN", "position": "LW", "goals": 36, "assists": 39, "games": 82, "ppg": 0.91},
    "Jason Robertson": {"team": "DAL", "position": "LW", "goals": 29, "assists": 46, "games": 82, "ppg": 0.91},
    "Kyle Connor": {"team": "WPG", "position": "LW", "goals": 34, "assists": 38, "games": 82, "ppg": 0.88},
    "William Karlsson": {"team": "VGK", "position": "C", "goals": 23, "assists": 37, "games": 82, "ppg": 0.73},

    # 21-50 - Star players
    "JT Miller": {"team": "VAN", "position": "C", "goals": 26, "assists": 49, "games": 82, "ppg": 0.91},
    "Aleksander Barkov": {"team": "FLA", "position": "C", "goals": 22, "assists": 52, "games": 82, "ppg": 0.90},
    "Roope Hintz": {"team": "DAL", "position": "C", "goals": 28, "assists": 38, "games": 82, "ppg": 0.80},
    "Mika Zibanejad": {"team": "NYR", "position": "C", "goals": 26, "assists": 41, "games": 82, "ppg": 0.82},
    "Bo Horvat": {"team": "NYI", "position": "C", "goals": 33, "assists": 34, "games": 82, "ppg": 0.82},
    "Mark Scheifele": {"team": "WPG", "position": "C", "goals": 26, "assists": 39, "games": 82, "ppg": 0.79},
    "Jonathan Huberdeau": {"team": "CGY", "position": "LW", "goals": 25, "assists": 52, "games": 82, "ppg": 0.94},
    "Brad Marchand": {"team": "BOS", "position": "LW", "goals": 29, "assists": 47, "games": 82, "ppg": 0.93},
    "Steven Stamkos": {"team": "TBL", "position": "C", "goals": 27, "assists": 41, "games": 82, "ppg": 0.83},
    "Ryan Nugent-Hopkins": {"team": "EDM", "position": "C", "goals": 28, "assists": 41, "games": 82, "ppg": 0.84},
    "Roman Josi": {"team": "NSH", "position": "D", "goals": 14, "assists": 53, "games": 82, "ppg": 0.82},
    "Rasmus Dahlin": {"team": "BUF", "position": "D", "goals": 15, "assists": 51, "games": 82, "ppg": 0.80},
    "Victor Hedman": {"team": "TBL", "position": "D", "goals": 9, "assists": 49, "games": 82, "ppg": 0.71},
    "Adam Fox": {"team": "NYR", "position": "D", "goals": 12, "assists": 48, "games": 82, "ppg": 0.73},
    "John Tavares": {"team": "TOR", "position": "C", "goals": 29, "assists": 36, "games": 82, "ppg": 0.79},
    "Claude Giroux": {"team": "OTT", "position": "C", "goals": 20, "assists": 43, "games": 82, "ppg": 0.77},
    "Nick Schmaltz": {"team": "UTAH", "position": "C", "goals": 22, "assists": 41, "games": 82, "ppg": 0.77},
    "Mark Stone": {"team": "VGK", "position": "RW", "goals": 20, "assists": 41, "games": 82, "ppg": 0.74},
    "Anze Kopitar": {"team": "LA", "position": "C", "goals": 20, "assists": 42, "games": 82, "ppg": 0.76},
    "Kevin Fiala": {"team": "LA", "position": "LW", "goals": 25, "assists": 39, "games": 82, "ppg": 0.78},
    "Adrian Kempe": {"team": "LA", "position": "C", "goals": 26, "assists": 25, "games": 82, "ppg": 0.62},
    "Vincent Trocheck": {"team": "NYR", "position": "C", "goals": 22, "assists": 39, "games": 82, "ppg": 0.74},
    "Nicholas Suzuki": {"team": "MTL", "position": "C", "goals": 20, "assists": 46, "games": 82, "ppg": 0.80},
    "Brady Tkachuk": {"team": "OTT", "position": "LW", "goals": 37, "assists": 38, "games": 82, "ppg": 0.91},
    "Patrick Kane": {"team": "DET", "position": "RW", "goals": 20, "assists": 47, "games": 82, "ppg": 0.82},
    "William Nylander": {"team": "TOR", "position": "RW", "goals": 33, "assists": 34, "games": 82, "ppg": 0.82},
    "Mathew Barzal": {"team": "NYI", "position": "C", "goals": 23, "assists": 39, "games": 82, "ppg": 0.76},
    "Evander Kane": {"team": "EDM", "position": "LW", "goals": 24, "assists": 28, "games": 82, "ppg": 0.63},
    "Tim Stutzle": {"team": "OTT", "position": "C", "goals": 26, "assists": 39, "games": 82, "ppg": 0.79},
    "Anthony Cirelli": {"team": "TBL", "position": "C", "goals": 20, "assists": 38, "games": 82, "ppg": 0.71},
    "Ondrej Palat": {"team": "NJ", "position": "LW", "goals": 20, "assists": 31, "games": 82, "ppg": 0.62},
    "Tyler Seguin": {"team": "DAL", "position": "C", "goals": 24, "assists": 34, "games": 82, "ppg": 0.71},
    "Jamie Benn": {"team": "DAL", "position": "LW", "goals": 18, "assists": 35, "games": 82, "ppg": 0.65},
    "Alex DeBrincat": {"team": "DET", "position": "RW", "goals": 27, "assists": 33, "games": 82, "ppg": 0.73},
    "Lucas Raymond": {"team": "DET", "position": "RW", "goals": 31, "assists": 41, "games": 82, "ppg": 0.88},
    "Dougie Hamilton": {"team": "NJD", "position": "D", "goals": 12, "assists": 47, "games": 82, "ppg": 0.72},
    "Drew Doughty": {"team": "LA", "position": "D", "goals": 10, "assists": 48, "games": 82, "ppg": 0.71},
    "Mikhail Sergachev": {"team": "TBL", "position": "D", "goals": 11, "assists": 42, "games": 82, "ppg": 0.65},
    "Kris Letang": {"team": "PIT", "position": "D", "goals": 12, "assists": 43, "games": 82, "ppg": 0.67},
    "John Carlson": {"team": "WSH", "position": "D", "goals": 11, "assists": 43, "games": 82, "ppg": 0.66},
    "Brent Burns": {"team": "CAR", "position": "D", "goals": 10, "assists": 47, "games": 82, "ppg": 0.70},
    "Noah Dobson": {"team": "NYI", "position": "D", "goals": 14, "assists": 40, "games": 82, "ppg": 0.66},

    # 51-80 - More solid players
    "David Krejci": {"team": "FLA", "position": "C", "goals": 16, "assists": 35, "games": 82, "ppg": 0.62},
    "Andrei Vasilevskiy": {"team": "TBL", "position": "G", "goals": 0, "assists": 0, "games": 82, "ppg": 0.0},
    "Connor Hellebuyck": {"team": "WPG", "position": "G", "goals": 0, "assists": 0, "games": 82, "ppg": 0.0},
    "Andrei Svechnikov": {"team": "CAR", "position": "LW", "goals": 23, "assists": 37, "games": 82, "ppg": 0.73},
    "Sebastian Aho": {"team": "CAR", "position": "C", "goals": 29, "assists": 36, "games": 82, "ppg": 0.79},
    "Jack Eichel": {"team": "VGK", "position": "C", "goals": 25, "assists": 39, "games": 82, "ppg": 0.78},
    "Alex Pietrangelo": {"team": "VGK", "position": "D", "goals": 11, "assists": 40, "games": 82, "ppg": 0.62},
    "Shea Theodore": {"team": "VGK", "position": "D", "goals": 13, "assists": 36, "games": 82, "ppg": 0.60},
    "Nazem Kadri": {"team": "CGY", "position": "C", "goals": 28, "assists": 39, "games": 82, "ppg": 0.82},
    "Yegor Sharangovich": {"team": "CGY", "position": "RW", "goals": 31, "assists": 39, "games": 82, "ppg": 0.85},
    "MacKenzie Weegar": {"team": "CGY", "position": "D", "goals": 11, "assists": 34, "games": 82, "ppg": 0.55},
    "Tage Thompson": {"team": "BUF", "position": "C", "goals": 28, "assists": 38, "games": 82, "ppg": 0.80},
    "Alex Tuch": {"team": "BUF", "position": "RW", "goals": 28, "assists": 33, "games": 82, "ppg": 0.74},
    "Jeff Skinner": {"team": "BUF", "position": "LW", "goals": 26, "assists": 31, "games": 82, "ppg": 0.70},
    "Casey Mittelstadt": {"team": "BUF", "position": "C", "goals": 23, "assists": 38, "games": 82, "ppg": 0.74},
    "Owen Power": {"team": "BUF", "position": "D", "goals": 8, "assists": 35, "games": 82, "ppg": 0.52},
    "Matt Duchene": {"team": "DAL", "position": "C", "goals": 20, "assists": 30, "games": 82, "ppg": 0.61},
    "Miro Heiskanen": {"team": "DAL", "position": "D", "goals": 6, "assists": 40, "games": 82, "ppg": 0.56},
    "Thomas Harley": {"team": "DAL", "position": "D", "goals": 10, "assists": 36, "games": 82, "ppg": 0.56},
    "Nico Hischier": {"team": "NJD", "position": "C", "goals": 21, "assists": 36, "games": 82, "ppg": 0.70},
    "Tim Meier": {"team": "NJD", "position": "RW", "goals": 26, "assists": 30, "games": 82, "ppg": 0.68},
    "Jesper Bratt": {"team": "NJD", "position": "LW", "goals": 25, "assists": 33, "games": 82, "ppg": 0.71},
    "Brock Boeser": {"team": "VAN", "position": "RW", "goals": 40, "assists": 33, "games": 82, "ppg": 0.89},
    "Conor Garland": {"team": "VAN", "position": "RW", "goals": 19, "assists": 26, "games": 82, "ppg": 0.55},
    "Filip Hronek": {"team": "VAN", "position": "D", "goals": 7, "assists": 35, "games": 82, "ppg": 0.51},
    "Carson Soucy": {"team": "MIN", "position": "D", "goals": 9, "assists": 31, "games": 82, "ppg": 0.49},
    "Jonas Brodin": {"team": "MIN", "position": "D", "goals": 4, "assists": 26, "games": 82, "ppg": 0.37},
    "Jared Spurgeon": {"team": "MIN", "position": "D", "goals": 8, "assists": 28, "games": 82, "ppg": 0.44},
    "Mats Zuccarello": {"team": "MIN", "position": "RW", "goals": 22, "assists": 32, "games": 82, "ppg": 0.66},
    "Ryan Hartman": {"team": "MIN", "position": "C", "goals": 15, "assists": 25, "games": 82, "ppg": 0.49},
    "Marcus Foligno": {"team": "MIN", "position": "LW", "goals": 16, "assists": 25, "games": 82, "ppg": 0.50},
    "Clayton Keller": {"team": "ARI", "position": "RW", "goals": 27, "assists": 37, "games": 82, "ppg": 0.78},
    "Barrett Hayes": {"team": "CHI", "position": "C", "goals": 18, "assists": 34, "games": 82, "ppg": 0.63},
    "Connor Bedard": {"team": "CHI", "position": "C", "goals": 22, "assists": 39, "games": 82, "ppg": 0.74},
    "Phil Kessel": {"team": "VEG", "position": "RW", "goals": 24, "assists": 28, "games": 82, "ppg": 0.63},
}
